name: Replicate to Public Repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Clone public repo
      - name: Clone public repo
        run: |
          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/visitafrica21-dotcom/NextStop-Africa-Tours-Public.git out

      # Replicate files to public repo
      - name: Replicate Content
        run: |
          # Use rsync to synchronize everything except .git, .github and the 'out' folder
          rsync -av --delete --exclude '.git' --exclude '.github' --exclude 'out' ./ out/

      # Push to public repo
      - name: Deploy
        run: |
          cd out
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Replicate private repo content" || echo "No changes to commit"
          git push